"""initial migration

Revision ID: 568a5b98e667
Revises: 
Create Date: 2017-09-16 10:56:44.556058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568a5b98e667'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
