"""add sex for User

Revision ID: a2e7201302ea
Revises: 568a5b98e667
Create Date: 2017-09-16 11:02:09.216495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e7201302ea'
down_revision = '568a5b98e667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.Integer(), nullable=True, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    # ### end Alembic commands ###
