# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMList' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Mantle'
  pod 'ReactiveCocoa', '~> 2.5'
  pod 'Masonry'

  # Pods for MVVMList

end

target 'loginDemo' do
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'Masonry'
end
